### ISSUE TITLE
[bug] Error: A critical and unhandled exception has occurred:

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/EIP-Bot#94] opened 2022-07-09 06:22 UTC
Unfortunately, there is no stack trace for some reason.  Also, there is an unhandled promise somewhere which makes debugging even harder.
```
#### Testing For Type updateEIP ####
-- Testing Must Have --
-- Testing Must Not Have --
!! is type updateEIP
eip-4519.md passed!
A critical and unhandled exception has occurred:
	Message: not found
	Data: (there is no data for this error)(cc @alita-moore, @mryalamanchi)
Error: A critical and unhandled exception has occurred:
	Message: not found
	Data: (there is no data for this error)(cc @alita-moore, @mryalamanchi)
(node:1725) UnhandledPromiseRejectionWarning: A critical and unhandled exception has occurred:
	Message: not found
	Data: (there is no data for this error)(cc @alita-moore, @mryalamanchi)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1725) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1725) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: Process completed with exit code 1.
```

**Comment by MicahZoltu** [comment] 2022-07-09 06:23
PR that caused the error (multiple runs of the bot, same error):
https://github.com/ethereum/EIPs/pull/5155/files

It updates some author contacts (email to github) and it modifies some images.  Either could potentially be related to the root cause of the exception.

**Comment by Pandapip1** [comment] 2022-07-09 17:33
Found the issue in the PR. Duplicate of #63

**Closed** 2022-07-10 05:35 UTC
