### ISSUE TITLE
Warn about solidity in assets directory

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/EIP-Bot#74] opened 2022-04-20 18:31 UTC
_Originally from #55_

In the Specification section, suggest to replace all links to solidity files to inline versions.

**Comment by JEAlfonsoP** [comment] 2022-04-22 03:41
I will work on it.

**Comment by MicahZoltu** [comment] 2022-05-01 10:09
All *external* links, or do you think we should suggest replacing links like `../assets/eip-####/file.sol` as well?

**Comment by Pandapip1** [comment] 2022-05-01 16:21
I'd prefer it if the bot replaced all links to solidity code with code blocks.

**Comment by MicahZoltu** [comment] 2022-05-02 13:02
Currently, we tell people who link to external code that they should either inline the code, or add it to `../assets/eip-####/file.sol`.  Are you suggesting that we instead tell them they should inline it and not give them the option of adding it to `../assets/eip-####/file.sol`?

If so, I'm curious about the reasoning for such a change?  It isn't clear to me what benefit we gain by disallowing code in assets.

**Comment by JEAlfonsoP** [comment] 2022-05-02 21:22
I am confused, original action was just to warn  or suggest to replace all links to solidity files to inline versions. !!
Please could we agree on the action for this issue so I can propose a possible solution (i.e. warning the author about it before merge..)

**Comment by Pandapip1** [comment] 2022-05-02 21:51
> It isn't clear to me what benefit we gain by disallowing code in assets.

I agree - if anything, this makes EIPs more verbose at the expense of readability. EIPs should be for reading, assets should be for examining.

**Comment by JEAlfonsoP** [comment] 2022-05-05 06:01
If I understood this, action would be to warn author about replace links to solidity files to inline versions. 
If this is the case a PR will be created right away.

**Comment by MicahZoltu** [comment] 2022-05-05 15:22
The bot would parse the whole EIP and look for any external links.  If it finds one that ends in `.sol`, it will comment on that line and recommend the user include the code inline in the EIP, rather than externally.

**Comment by JEAlfonsoP** [comment] 2022-05-07 03:38
Question: 
Do we want the bot to warn while parse /[\S]*/*[\S]*\.sol  and recommend inline coding for each appearance or do we actually want to modify PR body and "comment" in it for each appearance ?

/[\S]*/*[\S]*\.sol

**Comment by MicahZoltu** [comment] 2022-05-07 11:22
I think `/[\S]/[\S]*.sol` is too restrictive as it would catch `../assets/eip-####/foo.sol`.  I think we want something like `http\S+.sol`.

When we find a match, it should at least fail CI.  Second best option would be to let the user know in a comment what the problem is.  Third best option would be to comment directly on the line with the external link.  Fourth best option would be to collect this error up along with any others and submit a PR review with the feedback.

I recommend we start with the first option (just fail CI with a console.log), and then we can iterate/improve on it later.

**Comment by Pandapip1** [comment] 2022-05-07 12:30
There are legitimate use-cases for solidity in the assets directory, however. I'd prefer if it just warned the user.

**Comment by MicahZoltu** [comment] 2022-05-08 03:00
Our policy on external links is quite strict at the moment, so I have a strong preference for failure over warning.  Why do you think we should only warn?

**Comment by Pandapip1** [comment] 2022-05-08 13:53
I was talking about internal links to files in the assets directory. I agree external links should fail PR unless an editor approves it.

**Comment by MicahZoltu** [comment] 2022-05-09 06:18
Hmm, my interpretation of this issue is that it is referring to *external* links to solidity files, which is incredibly common for EIP authors to include.

**Comment by MicahZoltu** [comment] 2022-05-09 06:18
I don't think we should do anything at all if someone has a correctly formed internal link to a `.sol` file.  It is up to the individual authors whether they think inline is better/worse than `../assets`.

**Comment by SamWilsn** [comment] 2022-05-09 21:13
So to summarize:

* Relative (aka internal) links, which may take the form of `[Something.sol](../assets/eip-XXXX/Something.sol)`, **do not** generate a warning/error/comment. They also **do not** block the merge.

 * Absolute (aka external) links, which may take the form of `[Something.sol](http://example.com/Something.sol)`, **do** generate a warning/error/comment directing the author to either inline the file or place it in the assets directory. They also **do** block the merge.

**Comment by JEAlfonsoP** [comment] 2022-05-17 23:42
done (for approval)
`https://github.com/ethereum/EIP-Bot/pull/83/commits/ebb29f167718ac319087f166ce127701a70e8ecf`
https://github.com/ethereum/EIP-Bot/pull/83/commits/ebb29f167718ac319087f166ce127701a70e8ecf

**Comment by Pandapip1** [comment] 2022-08-10 17:18
Fixed in eipw.

**Closed by Pandapip1** 2022-08-10 17:18 UTC
